In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [5]:
pulse=pd.read_csv('Downloads\pulsar_stars.csv')

In [19]:
pulse.head()

Mean of the integrated profile  \
0                       140.562500   
1                       102.507812   
2                       103.015625   
3                       136.750000   
4                        88.726562   

    Standard deviation of the integrated profile  \
0                                      55.683782   
1                                      58.882430   
2                                      39.341649   
3                                      57.178449   
4                                      40.672225   

    Excess kurtosis of the integrated profile  \
0                                   -0.234571   
1                                    0.465318   
2                                    0.323328   
3                                   -0.068415   
4                                    0.600866   

    Skewness of the integrated profile   Mean of the DM-SNR curve  \
0                            -0.699648                   3.199833   
1                            -0.515088                   1.677258   
2                             1.051164                   3.121237   
3                            -0.636238                   3.642977   
4                             1.123492                   1.178930   

    Standard deviation of the DM-SNR curve  \
0                                19.110426   
1                                14.860146   
2                                21.744669   
3                                20.959280   
4                                11.468720   

    Excess kurtosis of the DM-SNR curve   Skewness of the DM-SNR curve  \
0                              7.975532                      74.242225   
1                             10.576487                     127.393580   
2                              7.735822                      63.171909   
3                              6.896499                      53.593661   
4                             14.269573                     252.567306   

   target_class  
0             0  
1             0  
2             0  
3             0  
4             0

In [6]:
pulse.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17898 entries, 0 to 17897
Data columns (total 9 columns):
 Mean of the integrated profile                  17898 non-null float64
 Standard deviation of the integrated profile    17898 non-null float64
 Excess kurtosis of the integrated profile       17898 non-null float64
 Skewness of the integrated profile              17898 non-null float64
 Mean of the DM-SNR curve                        17898 non-null float64
 Standard deviation of the DM-SNR curve          17898 non-null float64
 Excess kurtosis of the DM-SNR curve             17898 non-null float64
 Skewness of the DM-SNR curve                    17898 non-null float64
target_class                                     17898 non-null int64
dtypes: float64(8), int64(1)
memory usage: 1.2 MB


In [20]:
pulse['target_class'].unique()

array([0, 1], dtype=int64)

In [10]:
X=pulse.drop('target_class',axis=1)
y=pulse['target_class']

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [28]:
from sklearn.linear_model import SGDClassifier
sgd_clf = SGDClassifier(random_state=42)
sgd_clf.fit(X_train, y_train)
y_predict=sgd_clf.predict(X_test)

In [24]:
from sklearn.model_selection import cross_val_score
cross_val_score(sgd_clf,X_train, y_train,cv=3)

array([0.96857981, 0.97380553, 0.97191953])

In [30]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_predict)

array([[3120,  139],
       [  38,  283]], dtype=int64)

In [38]:
from sklearn.metrics import precision_score,recall_score,f1_score

In [36]:
precision_score(y_test,y_predict)

0.6706161137440758

In [37]:
recall_score(y_test,y_predict)

0.881619937694704

In [39]:
f1_score(y_test,y_predict)

0.7617765814266487

In [41]:
from sklearn.metrics import precision_recall_curve
precision_recall_curve(y_test,y_predict)

(array([0.0896648 , 0.67061611, 1.        ]),
 array([1.        , 0.88161994, 0.        ]),
 array([0, 1], dtype=int64))

In [42]:
print('hdsfs')

hdsfs
